//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/CursorController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CursorController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CursorController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CursorController"",
    ""maps"": [
        {
            ""name"": ""Mouse"",
            ""id"": ""fcd35aa0-386e-4aa9-829f-7427791943fe"",
            ""actions"": [
                {
                    ""name"": ""click"",
                    ""type"": ""Button"",
                    ""id"": ""9ba7b1cc-9daa-4ca1-8005-6a55c5719b26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Postion"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9a21041e-97b8-4a8a-bea1-cec97d817c40"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c5846e85-3f26-4db0-abca-67a4f74df10d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a34c3e96-fdc7-431f-bc53-f2621efd5579"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Postion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Mouse
        m_Mouse = asset.FindActionMap("Mouse", throwIfNotFound: true);
        m_Mouse_click = m_Mouse.FindAction("click", throwIfNotFound: true);
        m_Mouse_Postion = m_Mouse.FindAction("Postion", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mouse
    private readonly InputActionMap m_Mouse;
    private IMouseActions m_MouseActionsCallbackInterface;
    private readonly InputAction m_Mouse_click;
    private readonly InputAction m_Mouse_Postion;
    public struct MouseActions
    {
        private @CursorController m_Wrapper;
        public MouseActions(@CursorController wrapper) { m_Wrapper = wrapper; }
        public InputAction @click => m_Wrapper.m_Mouse_click;
        public InputAction @Postion => m_Wrapper.m_Mouse_Postion;
        public InputActionMap Get() { return m_Wrapper.m_Mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void SetCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterface != null)
            {
                @click.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @click.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @click.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @Postion.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnPostion;
                @Postion.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnPostion;
                @Postion.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnPostion;
            }
            m_Wrapper.m_MouseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @click.started += instance.OnClick;
                @click.performed += instance.OnClick;
                @click.canceled += instance.OnClick;
                @Postion.started += instance.OnPostion;
                @Postion.performed += instance.OnPostion;
                @Postion.canceled += instance.OnPostion;
            }
        }
    }
    public MouseActions @Mouse => new MouseActions(this);
    public interface IMouseActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnPostion(InputAction.CallbackContext context);
    }
}
